[build]
  publish = "public/"
  functions = "functions/"
  command = "npm run lint && npm run test && ALGOLIA_APP_ID=$ALGOLIA_APP_ID ALGOLIA_SEARCH_ONLY_API_KEY=$ALGOLIA_SEARCH_ONLY_API_KEY ALGOLIA_INDEX_NAME=$ALGOLIA_INDEX_NAME npm run build"
[[redirects]]
  from="/api/*"
  to="/.netlify/functions/:splat"
  status=200
